#!/usr/bin/python3
"""fatorize given set of  numbers to product of two smaller numbers"""
from sys import argv



def factorize(number)

    i = 2
    
    if number_to_check < 2:
        return
    
    while number_to_check % i:
        i += 1
    print("{:.0f}=:.0f}*{:.0f}".format(number_to_check, nuber_to_check / i, i))
if len(argv) !=2:
    exit()
    
try:
    with open(argv[1]) as file:
        line = file.readline()
        
        while line != "":
            number_to_check = int(line.split('\n')[0])
            factorize(number_to_check)
            line = file.readline()
except:
    pass
